spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/ecommerce
    username: prod_user
    password: prod_password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

  data:
    redis:
      host: prod-redis
      port: 6379

  cache:
    type: redis

  app:
    jwtSecret: CHANGE_ME_PROD_SECRET
    jwtExpirationMs: 3000000
    jwtCookieName: token

logging:
  level:
    com.buybuy.project: INFO
