spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  app:
    jwtSecret: mySecretKey1239129752aawbdpwkfpawfoajworjafoj24723
    jwtExpirationMs: 3000000
    jwtCookieName: token

project:
  image: images/

logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    com.buybuy.project: DEBUG


# ===== Management / Actuator =====
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: buybuy

# ===== Resilience4j Retry and Rate limiting =====
resilience4j:
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - com.buybuy.project.exceptions.APIException

  ratelimiter:
    instances:
      productRateLimiter:
        limit-for-period: 3
        limit-refresh-period: 10s
        timeout-duration: 0


open:
  api:
    title: API-services document
    version: v1.0.0
    description: Description
    serverUrl: http://domain.vn/license
    serverName: Server Test
