spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  app:
    jwtSecret: mySecretKey1239129752aawbdpwkfpawfoajworjafoj24723
    jwtExpirationMs: 3000000
    jwtCookieName: token

project:
  image: images/

logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    com.buybuy.project: DEBUG

open:
  api:
    title: API-services document
    version: v1.0.0
    description: Description
    serverUrl: http://domain.vn/license
    serverName: Server Test
